apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photos-pv
  labels:
    app: immich
    component: photos-storage
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: immich-photos-pv
    volumeAttributes:
      server: "CHANGE_ME_NFS_SERVER_IP"
      share: "/volume2/immich/photos"
      mountOptions: "nolock,nfsvers=3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-pvc
  namespace: immich
  labels:
    app: immich
    component: photos-storage
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Ti
  volumeName: immich-photos-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-redis-pv
  labels:
    app: immich
    component: redis-storage
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: immich-redis-pv
    volumeAttributes:
      server: "CHANGE_ME_NFS_SERVER_IP"
      share: "/volume2/immich/redis"
      mountOptions: "nolock,nfsvers=3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis-pvc
  namespace: immich
  labels:
    app: immich
    component: redis-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 15Gi
  volumeName: immich-redis-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql-pvc
  namespace: immich
  labels:
    app: immich
    component: postgresql-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-ml-cache-pv
  labels:
    app: immich
    component: ml-cache-storage
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: immich-ml-cache-pv
    volumeAttributes:
      server: "CHANGE_ME_NFS_SERVER_IP"
      share: "/volume2/immich/ml-cache"
      mountOptions: "nolock,nfsvers=3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache-pvc
  namespace: immich
  labels:
    app: immich
    component: ml-cache-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 25Gi
  volumeName: immich-ml-cache-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
  labels:
    app: immich
    component: library-storage
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: immich-library-pv
    volumeAttributes:
      server: "CHANGE_ME_NFS_SERVER_IP"
      share: "/volume2/immich/library"
      mountOptions: "nolock,nfsvers=3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
  labels:
    app: immich
    component: library-storage
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Ti
  volumeName: immich-library-pv
