apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-env
  namespace: plex
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: plex-env
    creationPolicy: Owner
  data:
    - secretKey: PLEX_CLAIM
      remoteRef:
        key: homelab/plex
        property: PLEX_CLAIM
